spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thogakade
    username: root
    password: 1234

  flyway:
    baseline-on-migrate: true

  spring:
    main:
      allow-bean-definition-overriding=true: